### ISSUE TITLE
[Question] Is there a way to have multiple chats for a single user's browser session?

### ISSUE THREAD

**Issue by wodow** [papercups-io/chat-widget#36] opened 2020-08-28 17:00 UTC
I am trying to let a single browser user have multiple, isolated chat sessions at once, on different web pages on the same domain. Is there a way to force this to happen? I am happy for them, for the moment, to appear as multiple customers.

I have tried to provide a different `external_id` in the config in each place when I would like an isolated/seperate chat session. The call to `https://app.papercups.io/api/customers/identify` sends the unique `external_id` but then always returns the same `customer_id`.

It's a great piece of software -- looking forward to using it more!

**Comment by reichert621** [comment] 2020-08-28 17:31
hey @wodow! hmm, if different `external_id`s are returning the same `customer_id` that sounds like a bug... let me look into this a bit more.

**Comment by wodow** [comment] 2020-08-31 12:42
Thanks for looking into it.

I've tried setting all three attributes of the `customer` object (`name`, `email`, `external_id`) to a unique values each time, but the still get the same chat session. Seems like it's entirely based on the browser session / cookies or similar.

**Comment by wodow** [comment] 2020-08-31 13:06
Possible workaround I'm trying out: clear Local Storage before every init of Papercups.

**Comment by reichert621** [comment] 2020-08-31 13:37
yeah I think clearing local storage will work in the meantime... looks like the bug here is that if we don't find a customer on our backend matching the external id you provide, we fall back to whatever is cached in local storage. 

the expected behavior should be: don't fall back to whatever is cached if an external id is provided; in other words, only use the cached value if no external id is provided.

i'll try to fix this soon! (got a lot of other things on my plate at the moment 😅 )

**Comment by reichert621** [comment] 2020-09-01 21:12
hey @wodow -- this should be fixed now! (feel free to reopen if you're still seeing the issue though)

**Closed by reichert621** 2020-09-01 21:12 UTC

**Comment by wodow** [comment] 2020-09-18 09:14
Great -- speedy! Thank you. I haven't tried removing the hack yet, but will do and report back if problems.
